# -*- coding: utf-8 -*-
"""NLP2(KunalChauhan).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12tx2ENBMLrHHW92Izje3UnNf1VhcWymh
"""

pip install PyPDF2

import csv
import PyPDF2

# Open the PDF file
pdf_file = 'Data Science.pdf'

with open(pdf_file, 'rb') as file:
    # Create a PDF reader object
    pdf_reader = PyPDF2.PdfFileReader(file)

    # Extract text from each page of the PDF
    text = ''
    for page_num in range(pdf_reader.numPages):
        page = pdf_reader.getPage(page_num)
        text += page.extract_text()

    # Store the extracted text in a CSV file
    csv_file = 'pdf_text.csv'

    with open(csv_file, 'w', newline='', encoding='utf-8') as file:
        writer = csv.writer(file)
        writer.writerow(['Text'])
        writer.writerow([text])

    print('Text extracted and stored in', csv_file)

# Count occurrences of each word in the text
word_counts = {}

# Split the text into words and count occurrences
words = text.lower().split()
for word in words:
    word_counts[word] = word_counts.get(word, 0) + 1

# Find the most repeated word
most_repeated_word = max(word_counts, key=word_counts.get)
repeat_count = word_counts[most_repeated_word]

print('Most repeated word:', most_repeated_word)
print('Number of occurrences:', repeat_count)