# -*- coding: utf-8 -*-
"""Python10(KunalChauhan).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12tx2ENBMLrHHW92Izje3UnNf1VhcWymh
"""

import nltk
from nltk.tokenize import word_tokenize
from nltk.tag import pos_tag
from collections import defaultdict

def count_pos_tags(text):
    # Tokenize the text into words
    words = word_tokenize(text)
    
    # Perform part-of-speech tagging
    tagged_words = pos_tag(words)
    
    # Initialize counts dictionary
    counts = defaultdict(int)
    
    # Count the number of verbs, nouns, pronouns, and adjectives
    for word, tag in tagged_words:
        if tag.startswith('VB'):  # Verb
            counts['verbs'] += 1
        elif tag.startswith('NN'):  # Noun
            counts['nouns'] += 1
        elif tag == 'PRP' or tag == 'PRP$':  # Pronoun
            counts['pronouns'] += 1
        elif tag.startswith('JJ'):  # Adjective
            counts['adjectives'] += 1
    
    return counts

# Test the function with an example phrase
phrase = "The quick brown fox jumps over the lazy dog"
counts = count_pos_tags(phrase)
print(counts)

# Additional Test Case 1
# Test with a paragraph containing various types of words
paragraph = "I love eating delicious pizza. John is running in the park. The blue sky is beautiful."
counts = count_pos_tags(paragraph)
print(counts)

# Additional Test Case 2
# Test with a sentence containing only pronouns
sentence = "He, she, and they are going to the party."
counts = count_pos_tags(sentence)
print(counts)