# -*- coding: utf-8 -*-
"""Python8(KunalChauhan).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12tx2ENBMLrHHW92Izje3UnNf1VhcWymh
"""

import requests
import pandas as pd
import matplotlib.pyplot as plt

# Send a GET request to fetch the data from the API
url = 'http://api.tvmaze.com/singlesearch/shows?q=westworld&embed=episodes'
response = requests.get(url)
data = response.json()

# Extract relevant information from the data
seasons = data['_embedded']['seasons']
episodes = data['_embedded']['episodes']

# Create a DataFrame to store the episode data
df = pd.DataFrame(episodes)

# Convert the airdate column to datetime
df['airdate'] = pd.to_datetime(df['airdate'])

# Get all the overall ratings for each season
season_ratings = df.groupby('season')['rating'].mean()

# Plot the ratings for all the seasons
season_ratings.plot(kind='bar')
plt.xlabel('Season')
plt.ylabel('Average Rating')
plt.title('Ratings for Each Season')
plt.show()

# Get all the episode names with average rating more than 8 for every season
high_rated_episodes = df.groupby(['season', 'name'])['rating'].mean().reset_index()
high_rated_episodes = high_rated_episodes[high_rated_episodes['rating'] > 8]

# Get all the episode names that aired before May 2019
episodes_before_2019 = df[df['airdate'] < pd.to_datetime('2019-05-01')]['name']

# Get the episode name with the highest and lowest rating for each season
highest_rated_episodes = df.groupby('season').apply(lambda x: x.loc[x['rating'].idxmax()])['name']
lowest_rated_episodes = df.groupby('season').apply(lambda x: x.loc[x['rating'].idxmin()])['name']

# Get the summary for the most popular episode in every season
most_popular_episodes = df.groupby('season').apply(lambda x: x.loc[x['rating'].idxmax()])['summary']

# Print the results
print('Overall Ratings for Each Season:')
print(season_ratings)
print('\nEpisode Names with Average Rating > 8:')
print(high_rated_episodes)
print('\nEpisode Names Aired Before May 2019:')
print(episodes_before_2019)
print('\nEpisode with Highest Rating in Each Season:')
print(highest_rated_episodes)
print('\nEpisode with Lowest Rating in Each Season:')
print(lowest_rated_episodes)
print('\nSummary of Most Popular Episode in Each Season:')
print(most_popular_episodes)