# -*- coding: utf-8 -*-
"""Statistics10(KunalChauhan).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cyuUZAu6RZ-FtTwMsuSCY_0FZI2JLMfg
"""

from scipy.stats import binom

n = 500  # Number of trials (light bulbs)
p = 0.05  # Probability of success (defective bulb)

probability_20_defective = binom.pmf(20, n, p)
print("The probability that exactly 20 bulbs are defective:", probability_20_defective)

probability_at_least_10_defective = 1 - binom.cdf(9, n, p)
print("The probability that at least 10 bulbs are defective:", probability_at_least_10_defective)

probability_at_most_15_defective = binom.cdf(15, n, p)
print("The probability that at most 15 bulbs are defective:", probability_at_most_15_defective)

expected_defective_bulbs = n * p
print("On average, we would expect", expected_defective_bulbs, "defective bulbs in a batch of 500.")