# -*- coding: utf-8 -*-
"""Statistics11(KunalChauhan).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cyuUZAu6RZ-FtTwMsuSCY_0FZI2JLMfg
"""

import pandas as pd
from scipy.stats import f_oneway, levene, bartlett
from statsmodels.stats.multicomp import pairwise_tukeyhsd

# Load the data
data = pd.read_csv('https://raw.githubusercontent.com/Kuna1Chauhan/EDA/main/data11question.csv')


# a. Check distribution of classes
f_statistic, p_value = f_oneway(data['BP(Before)'], data['BP(After)'])
if p_value < 0.05:
    print("The distribution of the classes is not the same.")
else:
    print("The distribution of the classes is the same.")

# b. Check equality of variance
levene_statistic, levene_p_value = levene(data['BP(Before)'], data['BP(After)'])
bartlett_statistic, bartlett_p_value = bartlett(data['BP(Before)'], data['BP(After)'])
if levene_p_value < 0.05 or bartlett_p_value < 0.05:
    print("The variances between classes are not equal.")
else:
    print("The variances between classes are equal.")

# c. Perform LDA and QDA to compare their performance

# d. Check equality of means
# One-way ANOVA
f_statistic, p_value = f_oneway(data['BP(Before)'], data['BP(After)'])
if p_value < 0.05:
    print("There are significant differences in means between at least one pair of classes.")
else:
    print("The means of all classes are equal.")