# -*- coding: utf-8 -*-
"""Statistics8(KunalChauhan).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cyuUZAu6RZ-FtTwMsuSCY_0FZI2JLMfg
"""

import pandas as pd

data = pd.read_csv("https://raw.githubusercontent.com/Kuna1Chauhan/EDA/main/Anxiety%20-%20Sheet1.csv")
anxiety_before = data["Before therapy"]
anxiety_after = data["After therapy"]
from scipy.stats import wilcoxon

statistic, p_value = wilcoxon(anxiety_before, anxiety_after)
significance_level = 0.05

if p_value < significance_level:
    print("The therapy had a significant effect on anxiety levels.")
else:
    print("The therapy did not have a significant effect on anxiety levels.")